version: "3"

services:
  configurator:
    image: ${IMAGE:?No image set}:${VERSION:?No ERP version set}
    command:
      - configurator-entrypoint.sh
    environment:
      DB_HOST: ${DB_HOST:-db}
      DB_PORT: ${DB_PORT:-3306}
      REDIS_CACHE: ${REDIS_CACHE:-redis-cache:6379}
      REDIS_QUEUE: ${REDIS_QUEUE:-redis-queue:6379}
      REDIS_SOCKETIO: ${REDIS_SOCKETIO:-redis-socketio:6379}
      SOCKETIO_PORT: 9000
    volumes:
      - sites:/home/frappe/frappe-bench/sites

volumes:
  sites:
    driver_opts:
      type: "nfs4"
      o: "addr=${NFS_SERVER:-No NFS Server set},rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14"
      device: ":/erp/sites"